### ISSUE TITLE
Add elevator and strafe capabilities to flight simulation mode

### ISSUE THREAD

**Issue by just-sam-a** [IDREsandbox/vsim#2]
Add elevator and strafe capabilities to flight simulation mode (e.g., holding down the ALT key while holding down the left mouse button and moving the mouse up and down or side to side would result in an elevator or strafe motion)

**Comment by haoxiangzhx** [comment]
Finish. 
ALT and left mouse for elevator mode, ALT and right mouse key for strafe mode.
Put the executable folder called "Release_May17_2017_elevatorAndStrafe" in T:\Projects\_UCLA\vsim\ReleaseToTest
